In [4]:
import pandas as pd
import os

# Caminho da pasta de dados
data_folder = '/home/Projetos/ProjetosDocker/data'

# Listar todos os arquivos CSV
csv_files = [f for f in os.listdir(data_folder) if f.endswith('.csv')]
csv_files.sort()

print(f'Encontrados {len(csv_files)} arquivos CSV:')
for f in csv_files:
    print(f'  - {f}')

Encontrados 5 arquivos CSV:
  - data-1772046577622.csv
  - data-1772046611038.csv
  - data-1772046636697.csv
  - data-1772046649147.csv
  - data-1772046923950.csv

In [19]:
# Ler todos os arquivos CSV em um dicionário
dataframes = {}

for csv_file in csv_files:
    file_path = os.path.join(data_folder, csv_file)
    try:
        df = pd.read_csv(file_path)
        dataframes[csv_file] = df
        print(f'\n{csv_file}:')
        print(f'  Shape: {df.shape}')
        print(f'  Colunas: {list(df.columns)}')
    except Exception as e:
        print(f'Erro ao ler {csv_file}: {e}')

data-1772046577622.csv:
  Shape: (451, 19)
  Colunas: ['id', 'run_id', 'status', 'source', 'payable_id', 'supplier', 'document', 'history', 'due_date', 'amount', 'movement_id', 'movement_date', 'movementType', 'movement_desc', 'movement_balance', 'matched_movement_id', 'created_at', 'match_reason', 'match_score']

data-1772046611038.csv:
  Shape: (8, 6)
  Colunas: ['id', 'condominium_id', 'month', 'year', 'created_at', 'updated_at']

data-1772046636697.csv:
  Shape: (3, 17)
  Colunas: ['id', 'protocol_id', 'condominium_id', 'unique_id', 'account_hash', 'openfinance_id', 'bank_code', 'origin', 'period_start', 'period_end', 'balance_start', 'balance_end', 'total_transactions', 'payload', 'created_at', 'updated_at', 'pdf_url']

data-1772046649147.csv:
  Shape: (134, 14)
  Colunas: ['id', 'statement_id', 'condominium_id', 'account_hash', 'openfinance_id', 'transaction_date', 'amount', 'type', 'description', 'balance', 'transaction_id', 'unique_hash', 'created_at', 'updated_at']

data-1772046923950.csv:
  Shape: (6, 18)
  Colunas: ['id', 'unique_id', 'condominium_id', 'account_hash', 'openfinance_id', 'payer_cnpj', 'environment', 'status', 'period_start', 'period_end', 'requested_at', 'last_checked_at', 'request_payload', 'response_payload', 'error_code', 'error_message', 'created_at', 'updated_at']

In [20]:
# Ler e explorar o arquivo data-1772046577622.csv
df = dataframes['data-1772046577622.csv']

print('=== INFORMAÇÕES DO ARQUIVO ===')
print(f'Total de linhas: {df.shape[0]}')
print(f'Total de colunas: {df.shape[1]}')
print(f'\nTipos de dados:')
print(df.dtypes)
print(f'\n=== PRIMEIRAS 5 LINHAS ===')
df.head()

=== INFORMAÇÕES DO ARQUIVO ===
Total de linhas: 451
Total de colunas: 19

Tipos de dados:
id                         str
run_id                     str
status                     str
source                     str
payable_id                 str
supplier                   str
document               float64
history                    str
due_date                   str
amount                 float64
movement_id                str
movement_date              str
movementType               str
movement_desc              str
movement_balance       float64
matched_movement_id        str
created_at                 str
match_reason               str
match_score              int64
dtype: object

=== PRIMEIRAS 5 LINHAS ===

,id,run_id,status,source,payable_id,supplier,document,history,due_date,amount,movement_id,movement_date,movementType,movement_desc,movement_balance,matched_movement_id,created_at,match_reason,match_score
0,b19e0f3c-78da-400b-b05a-3f69b5acb2f8,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:153697,Ferreira Costa & Cia Ltda,153697.0,Material p/Manutenção Geral - Ferreira Costa &...,2026-02-21 03:00:00,786.98,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
1,5ff57402-0490-43bc-8831-d9b65ae914f8,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:173673,Luis Eduardo Oliveira dos Santos,173673.0,Manutenção Jardim - Manutenção Jardim - Luis E...,2026-02-18 03:00:00,1000.00,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
2,2b4087ff-4a17-4734-8e3f-0f57f4f9315c,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:180480,Ferreira Costa & Cia Ltda,180480.0,Material Elétrico - Ferreira Costa & Cia Ltda ...,2026-02-28 03:00:00,167.21,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
3,86988367-a60b-4cd8-866e-24f31e0b8c26,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:180617,RT Serviços e Apoio Administrativo,180617.0,Controladoria Taxa de Controladoria - RT Servi...,2026-02-05 03:00:00,1223.90,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
4,735c28a1-9347-45b5-8271-fcd1b2f233a7,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:184425,Alerta Tecnologia em Seg Monitorada,184425.0,Sistema de Alarme Manutenção Sistema de Alarme...,2026-02-10 03:00:00,275.00,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0

In [18]:
# Estatísticas e valores ausentes
print('=== VALORES AUSENTES ===')
print(df.isnull().sum())

print('\n=== ESTATÍSTICAS DAS COLUNAS NUMÉRICAS ===')
print(df.describe())

print('\n=== VALORES ÚNICOS POR COLUNA ===')
for col in df.select_dtypes(include='object').columns:
    unique_count = df[col].nunique()
    if unique_count <= 10:
        print(f'{col}: {unique_count} valores únicos')
        print(f'  Valores: {df[col].unique()[:10].tolist()}')
    else:
        print(f'{col}: {unique_count} valores únicos')

=== VALORES AUSENTES ===
id                       0
run_id                   0
status                   0
source                   0
payable_id              28
supplier                28
document                28
history                 28
due_date                28
amount                   0
movement_id            388
movement_date          388
movementType           388
movement_desc          388
movement_balance       388
matched_movement_id    416
created_at               0
match_reason             0
match_score              0
dtype: int64

=== ESTATÍSTICAS DAS COLUNAS NUMÉRICAS ===
            document        amount  movement_balance  match_score
count     423.000000    451.000000              63.0   451.000000
mean   207745.444444   2262.438625               0.0     0.416851
std     46777.191220   7404.060045               0.0     1.612198
min     54439.000000      0.190000               0.0     0.000000
25%    180081.000000      4.050000               0.0     0.000000
50%    204849.000000    272.950000               0.0     0.000000
75%    239354.500000   1471.000000               0.0     0.000000
max    290704.000000  67510.620000               0.0    11.000000

=== VALORES ÚNICOS POR COLUNA ===
id: 451 valores únicos
run_id: 6 valores únicos
  Valores: ['595ac07f-11b5-47e3-9251-89b42f4a989f', 'af333bc7-6084-4f38-a4de-a7bfaeae1f30', '79171799-c805-4bcc-b3f8-f47b9c3e1eed', '3045211f-c32f-44c6-aa49-0c78546a9c74', '986e7a83-ac6d-494e-9b4e-f75ae62e8348', 'aea297cb-350d-42ed-b412-bb226eb7eda2']
status: 3 valores únicos
  Valores: ['UNMATCHED', 'MATCHED', 'UNMATCHED_MOVEMENT']
source: 3 valores únicos
  Valores: ['OPEN', 'PAID', 'MOVEMENT']
payable_id: 423 valores únicos
supplier: 44 valores únicos
history: 208 valores únicos
due_date: 52 valores únicos
movement_id: 63 valores únicos
movement_date: 19 valores únicos
movementType: 1 valores únicos
  Valores: [nan, 'DEBIT']
movement_desc: 63 valores únicos
matched_movement_id: 35 valores únicos
created_at: 6 valores únicos
  Valores: ['2026-02-24 16:51:42.202', '2026-02-24 16:51:42.32', '2026-02-24 16:51:42.449', '2026-02-24 16:55:04.229', '2026-02-24 16:55:04.382', '2026-02-25 15:14:58.867']
match_reason: 6 valores únicos
  Valores: ['PENDING_NO_MATCH', 'PAID_NO_STATEMENT', 'UNMATCHED_MOVEMENT', 'VALUE_UNIQUE', 'VALUE_TEXT_DATE', 'VALUE_INVOICE_MATCH']

/tmp/ipykernel_3085078/3087785759.py:9: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [12]:
# Análise detalhada: Distribuição de Status e Fonte
print('=== DISTRIBUIÇÃO DE STATUS ===')
print(df['status'].value_counts())

print('\n=== DISTRIBUIÇÃO DE FONTE ===')
print(df['source'].value_counts())

print('\n=== DISTRIBUIÇÃO DE RAZÃO DE MATCH ===')
print(df['match_reason'].value_counts())

print('\n=== REGISTROS POR RUN_ID ===')
print(df['run_id'].value_counts())

=== DISTRIBUIÇÃO DE STATUS ===
status
MATCHED               332
UNMATCHED              91
UNMATCHED_MOVEMENT     28
Name: count, dtype: int64

=== DISTRIBUIÇÃO DE FONTE ===
source
PAID        330
OPEN         93
MOVEMENT     28
Name: count, dtype: int64

=== DISTRIBUIÇÃO DE RAZÃO DE MATCH ===
match_reason
PAID_NO_STATEMENT      297
PENDING_NO_MATCH        91
UNMATCHED_MOVEMENT      28
VALUE_TEXT_DATE         19
VALUE_UNIQUE            10
VALUE_INVOICE_MATCH      6
Name: count, dtype: int64

=== REGISTROS POR RUN_ID ===
run_id
aea297cb-350d-42ed-b412-bb226eb7eda2    102
3045211f-c32f-44c6-aa49-0c78546a9c74     93
986e7a83-ac6d-494e-9b4e-f75ae62e8348     91
79171799-c805-4bcc-b3f8-f47b9c3e1eed     76
af333bc7-6084-4f38-a4de-a7bfaeae1f30     53
595ac07f-11b5-47e3-9251-89b42f4a989f     36
Name: count, dtype: int64

In [13]:
# Top 10 Suppliers com mais registros
print('=== TOP 10 SUPPLIERS ===')
print(df['supplier'].value_counts().head(10))

print('\n=== ESTATÍSTICAS DE AMOUNT POR STATUS ===')
print(df.groupby('status')['amount'].agg(['count', 'sum', 'mean', 'min', 'max']))

print('\n=== DADOS CONSOLIDADOS ===')
print(f'Total de registros: {len(df)}')
print(f'Registros sem match: {len(df[df["status"] == "UNMATCHED"]) + len(df[df["status"] == "UNMATCHED_MOVEMENT"])}')
print(f'Taxa de match: {len(df[df["status"] == "MATCHED"]) / len(df) * 100:.2f}%')
print(f'Valor total: R$ {df["amount"].sum():,.2f}')

=== TOP 10 SUPPLIERS ===
supplier
1861                                  128
421                                   115
1720                                   65
2383                                   22
Receita Federal do Brasil              15
RT Serviços e Apoio Administrativo      6
Ferreira Costa & Cia Ltda               5
Ticket Serviços SA                      5
Funcionários                            5
Luis Eduardo Oliveira dos Santos        4
Name: count, dtype: int64

=== ESTATÍSTICAS DE AMOUNT POR STATUS ===
                    count        sum         mean    min       max
status
MATCHED               332  798689.54  2405.691386   0.19  67510.62
UNMATCHED              91  150972.65  1659.040110  10.00  14232.86
UNMATCHED_MOVEMENT     28   70697.63  2524.915357  22.99   8166.51

=== DADOS CONSOLIDADOS ===
Total de registros: 451
Registros sem match: 119
Taxa de match: 73.61%
Valor total: R$ 1,020,359.82

In [21]:
# Exibir o DataFrame completo
df.head(5)

,id,run_id,status,source,payable_id,supplier,document,history,due_date,amount,movement_id,movement_date,movementType,movement_desc,movement_balance,matched_movement_id,created_at,match_reason,match_score
0,b19e0f3c-78da-400b-b05a-3f69b5acb2f8,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:153697,Ferreira Costa & Cia Ltda,153697.0,Material p/Manutenção Geral - Ferreira Costa &...,2026-02-21 03:00:00,786.98,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
1,5ff57402-0490-43bc-8831-d9b65ae914f8,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:173673,Luis Eduardo Oliveira dos Santos,173673.0,Manutenção Jardim - Manutenção Jardim - Luis E...,2026-02-18 03:00:00,1000.00,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
2,2b4087ff-4a17-4734-8e3f-0f57f4f9315c,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:180480,Ferreira Costa & Cia Ltda,180480.0,Material Elétrico - Ferreira Costa & Cia Ltda ...,2026-02-28 03:00:00,167.21,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
3,86988367-a60b-4cd8-866e-24f31e0b8c26,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:180617,RT Serviços e Apoio Administrativo,180617.0,Controladoria Taxa de Controladoria - RT Servi...,2026-02-05 03:00:00,1223.90,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0
4,735c28a1-9347-45b5-8271-fcd1b2f233a7,595ac07f-11b5-47e3-9251-89b42f4a989f,UNMATCHED,OPEN,cndpagar:184425,Alerta Tecnologia em Seg Monitorada,184425.0,Sistema de Alarme Manutenção Sistema de Alarme...,2026-02-10 03:00:00,275.00,NaN,NaN,NaN,NaN,NaN,NaN,2026-02-24 16:51:42.202,PENDING_NO_MATCH,0